# Generated by Django 3.2.23 on 2023-12-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='slug',
        ),
    ]
